(()=>{'use strict';
const $=id=>document.getElementById(id),STORIES=window.STORY_CARDS||[],ELEMENTS=window.STORY_ELEMENTS||[];
const screens={setup:$('setup'),handoff:$('handoff'),secret:$('secretScreen'),ready:$('ready')};
const P=$('players'),S=$('spies'),N=$('names'),A=$('wordA'),B=$('wordB'),NA=$('noA'),NB=$('noB'),blind=$('blind'),toast=$('toast'),storyTheme=$('storyTheme'),storyOpening=$('storyOpening'),storyGoal=$('storyGoal');
const ARCHIVE_KEY='undercover_story_archive_v1',DRAFT_KEY='undercover_story_draft_v1';
const wordPairs=[['拿鐵','卡布奇諾'],['可樂','雪碧'],['貓','老虎'],['火鍋','麻辣燙'],['海邊','游泳池'],['吉他','烏克麗麗'],['電影','影集'],['咖啡','紅茶']];
const flavorPairs=[['檸檬','柑橘','A-01','B-01'],['茉莉','玫瑰','A-02','B-02'],['草莓','覆盆莓','A-03','B-03'],['藍莓','黑莓','A-04','B-04'],['香草','焦糖','A-05','B-05'],['巧克力','可可','A-06','B-06'],['杏仁','榛果','A-07','B-07'],['肉桂','丁香','A-08','B-08'],['紅茶','烏龍茶','A-09','B-09'],['蜂蜜','黑糖','A-10','B-10']];
let mode='flavor',state={players:[],roles:[],i:0,elements:[],storyteller:-1,lastStory:-1,storyLog:[],recordTurn:0,gameId:null};
const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function flash(t){toast.textContent=t;toast.classList.add('show');clearTimeout(flash.t);flash.t=setTimeout(()=>toast.classList.remove('show'),1400)}
function show(n){Object.values(screens).forEach(x=>x.classList.remove('active'));screens[n].classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function shuffle(x){x=[...x];for(let i=x.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function color(t){const p=['#ffd85b','#ff9d5c','#ef6f86','#a779e9','#72cfe6','#80d58c','#c8915b','#f2e1a0','#d95f5f','#8cc1ff'];let h=0;for(const c of t)h=(h*31+c.charCodeAt(0))>>>0;return p[h%p.length]}
function paintBottle(id,name,label){const el=$(id);if(!el)return;el.style.setProperty('--liquid',color(name||label||'AROMA'));const s=el.querySelector('span');if(s)s.textContent=label||'AROMA'}
function preview(){const a=A.value.trim()||'多數風味',b=B.value.trim()||'內鬼風味',an=NA.value.trim()||'A',bn=NB.value.trim()||'B';$('prevNameA').textContent=a;$('prevNameB').textContent=b;$('prevNoA').textContent='瓶號 '+an;$('prevNoB').textContent='瓶號 '+bn;paintBottle('prevBottleA',a,an);paintBottle('prevBottleB',b,bn)}
function presets(){const box=$('presets');box.innerHTML='';(mode==='flavor'?flavorPairs:wordPairs).forEach(([a,b,an,bn])=>{const x=document.createElement('button');x.type='button';x.className='chip';x.textContent=a+' / '+b;x.onclick=()=>{A.value=a;B.value=b;if(mode==='flavor'){NA.value=an||'A';NB.value=bn||'B'}preview();flash('已套用')};box.appendChild(x)})}
function applyStory(i){const [t,o,g]=STORIES[i];storyTheme.value=t;storyOpening.value=o;storyGoal.value=g;state.lastStory=i;flash('故事卡已套用：'+t)}
function randomStory(){if(!STORIES.length)return;let i=0;if(STORIES.length>1){do{i=Math.floor(Math.random()*STORIES.length)}while(i===state.lastStory)}applyStory(i)}
function storyPresets(){const box=$('storyPresets');box.innerHTML='';STORIES.forEach(([t],i)=>{const x=document.createElement('button');x.type='button';x.className='chip';x.textContent=t;x.onclick=()=>applyStory(i);box.appendChild(x)});$('storyCount').textContent=`共 ${STORIES.length} 組故事卡`}
function setMode(m){mode=m;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.mode===m));document.querySelectorAll('.flavorOnly').forEach(x=>x.classList.toggle('hidden',m!=='flavor'));document.querySelectorAll('.storyOnly').forEach(x=>x.classList.toggle('hidden',m!=='story'));document.querySelectorAll('.normalOnly').forEach(x=>x.classList.toggle('hidden',m==='story'));$('lab').classList.toggle('hidden',m!=='flavor');$('blindRow').classList.toggle('hidden',m!=='flavor');$('roleCountField').classList.toggle('hidden',m==='story');
if(m==='flavor'){$('heroFace').textContent='?';$('heroFace').style.background='var(--blue)';$('heroTitle').textContent='像素內鬼・風味瓶版';$('heroDesc').textContent='分配瓶號、輪流聞香、描述氣味，再找出不一樣的人。';$('labelA').textContent='多數風味';$('labelB').textContent='內鬼風味';$('presetLabel').textContent='相近風味快速配對';$('start').textContent='▶ 產生身分'}
else if(m==='word'){$('heroFace').textContent='ABC';$('heroFace').style.background='var(--green)';$('heroTitle').textContent='經典文字誰是內鬼';$('heroDesc').textContent='每個人秘密查看自己的詞，用一句話形容它，再從描述裡找出拿到不同詞的人。';$('labelA').textContent='平民詞';$('labelB').textContent='內鬼詞';$('presetLabel').textContent='快速詞組';$('start').textContent='▶ 產生身分'}
else{$('heroFace').textContent='✦';$('heroFace').style.background='var(--purple)';$('heroTitle').textContent='妙語說書人・故事接龍';$('heroDesc').textContent=`從 ${STORIES.length} 組故事世界中挑一題，邊說邊把每位玩家的段落記錄成完整故事。`;$('start').textContent='📖 開始今晚的故事';renderArchive()}
presets();preview()}
function spies(){const n=+P.value||6,max=Math.min(4,Math.max(1,Math.floor((n-1)/2))),now=+S.value||1;S.innerHTML='';for(let i=1;i<=max;i++)S.add(new Option(i+' 人',i));S.value=Math.min(now,max)}
function names(n){const a=N.value.split(/\n+/).map(x=>x.trim()).filter(Boolean).slice(0,n);return Array.from({length:n},(_,i)=>a[i]||'玩家 '+(i+1))}
function build(){const n=+P.value;state.players=names(n);state.i=0;if(mode==='story'){if(!storyTheme.value.trim()||!storyOpening.value.trim()||!storyGoal.value.trim()){flash('請把故事題目、開場與終點填完整');return false}state.storyteller=Math.floor(Math.random()*n);state.roles=Array.from({length:n},(_,i)=>i===state.storyteller?'storyteller':'weaver');state.elements=shuffle(ELEMENTS).slice(0,n);state.storyLog=[];state.recordTurn=0;state.gameId='story-'+Date.now();return true}const a=A.value.trim(),b=B.value.trim();if(!a||!b){flash('請輸入兩組內容');return false}if(a===b){flash('兩組內容要不同');return false}const s=+S.value;state.roles=shuffle([...Array(s).fill('spy'),...Array(n-s).fill('civilian')]);state.elements=[];state.storyteller=-1;return true}
function handoff(){const i=state.i;$('prog').textContent=`PLAYER ${i+1} / ${state.players.length}`;$('who').textContent=state.players[i];$('handoffStatus').textContent=mode==='story'?'STORY CARD':'♥ ♥ ♥';$('handoffHint').textContent=mode==='story'?'把手機交給這位玩家。每個人只看自己的故事角色與秘密提示。':'把手機交給這位玩家。確認旁邊沒有人偷看。';show('handoff')}
function secret(){const i=state.i;$('sprog').textContent=`PLAYER ${i+1} / ${state.players.length}`;$('storyPrompt').classList.add('hidden');$('word').classList.remove('hidden');if(mode==='story'){const teller=state.roles[i]==='storyteller';$('secretCard').className='secret '+(teller?'storyteller':'weaver');$('roleTag').textContent=teller?'STORYTELLER':'STORY WEAVER';$('role').textContent=teller?'你是說書人':'你是續寫者';$('word').classList.add('hidden');$('storyPrompt').classList.remove('hidden');$('storyPromptLabel').textContent=teller?'SECRET STORY DESTINATION':'SECRET STORY ELEMENT';$('storyPromptText').innerHTML=teller?`<strong style="font-size:20px">${esc(storyGoal.value.trim())}</strong><br><span style="font-size:11px">把大家的故事慢慢帶向這個終點，但不要直接把答案講出來。</span>`:`<strong style="font-size:20px">${esc(state.elements[i])}</strong><br><span style="font-size:11px">輪到你時，把這個元素自然藏進 1–3 句故事裡。</span>`;$('note').textContent=teller?'你知道終點，但不能硬轉彎。利用其他人的內容，把故事自然帶回你的方向。':'你不知道真正終點。先接住前一位玩家的劇情，再偷偷埋入自己的元素。';show('secret');return}
const spy=state.roles[i]==='spy',w=spy?B.value.trim():A.value.trim(),no=(spy?NB.value.trim():NA.value.trim())||(spy?'B':'A');$('secretCard').className='secret '+(spy?'spy':'');$('roleTag').textContent=spy?'UNDERCOVER':'CIVILIAN';$('role').textContent=spy?'你是內鬼':'你是平民';if(mode==='flavor'){$('word').textContent=blind.checked?'瓶號 '+no:w;$('note').textContent=spy?'你的風味與大多數人不同。描述氣味，但不要直接說瓶名或瓶號。':'聞香後描述一個特徵，別說瓶名或瓶號。'}else{$('word').textContent=w;$('note').textContent=spy?'你的詞和大多數人不同。保持冷靜，混進去。':'記住你的詞，描述時別講得太明顯。'}show('secret')}
function ready(){const f=mode==='flavor';$('storyReady').classList.toggle('hidden',mode!=='story');if(mode==='story'){$('readyIcon').textContent='📖';$('readyTitle').textContent='故事開始！';$('readyDesc').textContent='從開場句開始，依序每人補 1–3 句；說完就立刻記進故事簿。';$('publicStoryTitle').textContent=storyTheme.value.trim();$('publicOpening').textContent=storyOpening.value.trim();$('storyOrder').innerHTML='<strong>建議說故事順序：</strong><br>'+state.players.map((x,i)=>`${i+1}. ${esc(x)}`).join(' → ');$('goalSecret').textContent='？？？？？？';$('revealGoal').classList.remove('hidden');$('summary').innerHTML=`<strong>模式：</strong>📖 妙語說書人<br><strong>故事庫：</strong>${STORIES.length} 組<br><strong>玩家：</strong>${state.players.length} 人<br><strong>說書人：</strong>1 人（身分保密）<br><strong>記錄：</strong>每位玩家說完後加入故事簿，系統會建立本機草稿。`;$('readyWarn').textContent='✨ 最後先猜故事終點再揭曉；完成後可保存、複製或匯出 TXT。';initRecorder();show('ready');return}const n=state.roles.filter(x=>x==='spy').length;$('readyIcon').textContent='🕵️';$('readyTitle').textContent='所有人都看完了！';$('readyDesc').textContent=f?'開始聞香與描述。不要直接說出瓶名、瓶號或答案。':'開始描述。每人一句話，別把自己的詞講得太明顯。';$('summary').innerHTML=`<strong>模式：</strong>${f?'🧪 風味瓶誰是內鬼':'ABC 文字誰是內鬼'}<br><strong>玩家：</strong>${state.players.length} 人<br><strong>內鬼：</strong>${n} 人`;$('readyWarn').textContent='⚠ 這裡不顯示誰是內鬼；重新開始會重新洗牌。';show('ready')}
function currentStoryData(){return{id:state.gameId||('story-'+Date.now()),title:storyTheme.value.trim(),opening:storyOpening.value.trim(),goal:storyGoal.value.trim(),players:[...state.players],log:state.storyLog.map(x=>({...x})),savedAt:new Date().toISOString()}}
function storyText(d,withGoal=true){const lines=[`《${d.title||'未命名故事'}》`,'',d.opening||'',''];(d.log||[]).forEach((x,i)=>{lines.push(`${i+1}. ${x.player}：${x.text}`)});if(withGoal){lines.push('','— 故事終點 —',d.goal||'')}return lines.join('\n')}
function saveDraft(){try{localStorage.setItem(DRAFT_KEY,JSON.stringify(currentStoryData()));$('autosaveState').textContent='● 草稿已自動儲存'}catch(e){$('autosaveState').textContent='⚠ 無法使用本機儲存'}}
function loadArchive(){try{return JSON.parse(localStorage.getItem(ARCHIVE_KEY)||'[]')||[]}catch(e){return[]}}
function writeArchive(a){try{localStorage.setItem(ARCHIVE_KEY,JSON.stringify(a.slice(0,30)));return true}catch(e){flash('本機儲存空間不足');return false}}
function saveCurrentStory(){const d=currentStoryData(),a=loadArchive(),i=a.findIndex(x=>x.id===d.id);if(i>=0)a[i]=d;else a.unshift(d);if(writeArchive(a)){try{localStorage.removeItem(DRAFT_KEY)}catch(e){}flash('故事已保存到這台裝置');renderArchive()}}
function renderRecorder(){const box=$('recordTranscript');if(!state.storyLog.length){box.innerHTML='<div class="recordEmpty">故事還只有開場。每位玩家說完後，把內容加入這裡。</div>';return}box.innerHTML=state.storyLog.map((x,i)=>`<div class="recordLine"><b>${i+1}. ${esc(x.player)}</b><p>${esc(x.text)}</p></div>`).join('');box.scrollTop=box.scrollHeight}
function initRecorder(){const sel=$('recordPlayer');sel.innerHTML='';state.players.forEach((p,i)=>sel.add(new Option(`${i+1}. ${p}`,i)));sel.value=Math.min(state.recordTurn,state.players.length-1);$('recordText').value='';$('autosaveState').textContent='○ 尚未記錄';renderRecorder()}
function addRecord(){const text=$('recordText').value.trim();if(!text){flash('先輸入這位玩家說的故事');return}const idx=+$('recordPlayer').value||0;state.storyLog.push({player:state.players[idx]||('玩家 '+(idx+1)),text,time:Date.now()});state.recordTurn=(idx+1)%state.players.length;$('recordPlayer').value=state.recordTurn;$('recordText').value='';renderRecorder();saveDraft();$('recordText').focus()}
function undoRecord(){if(!state.storyLog.length){flash('目前沒有可撤銷的段落');return}const last=state.storyLog.pop();const idx=Math.max(0,state.players.indexOf(last.player));state.recordTurn=idx;$('recordPlayer').value=idx;renderRecorder();saveDraft();flash('已撤銷上一段')}
function clearRecord(){if(!state.storyLog.length)return;if(!confirm('確定清空這一局已記錄的所有段落？'))return;state.storyLog=[];state.recordTurn=0;$('recordPlayer').value=0;renderRecorder();saveDraft();flash('本局故事紀錄已清空')}
async function copyText(text){try{await navigator.clipboard.writeText(text);flash('故事全文已複製')}catch(e){const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();flash('故事全文已複製')}}
function downloadText(text,name){const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(name||'story').replace(/[\\/:*?"<>|]/g,'_')+'.txt';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function archiveDate(v){try{return new Intl.DateTimeFormat('zh-TW',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch(e){return''}}
function renderArchive(){const box=$('archiveList');if(!box)return;const items=[];try{const d=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(d&&d.title)items.push({...d,_draft:true})}catch(e){}loadArchive().forEach(x=>items.push(x));if(!items.length){box.innerHTML='<div class="archiveEmpty">尚無故事存檔。完成一局後按「💾 保存本局」就會出現在這裡。</div>';return}box.innerHTML=items.map((d,i)=>`<div class="archiveItem${d._draft?' draft':''}" data-id="${esc(d.id||'')}"><b>${d._draft?'✎ 自動草稿｜':''}${esc(d.title||'未命名故事')}</b><div class="archiveMeta">${archiveDate(d.savedAt)}・${(d.log||[]).length} 段</div><div class="row"><button data-act="copy" data-idx="${i}">複製</button><button data-act="download" data-idx="${i}">匯出 TXT</button><button data-act="delete" data-idx="${i}">${d._draft?'刪除草稿':'刪除'}</button></div></div>`).join('');box.querySelectorAll('button').forEach(btn=>btn.onclick=()=>{const d=items[+btn.dataset.idx],act=btn.dataset.act;if(act==='copy')copyText(storyText(d,true));else if(act==='download')downloadText(storyText(d,true),d.title);else{if(!confirm('確定刪除這份故事紀錄？'))return;if(d._draft){localStorage.removeItem(DRAFT_KEY)}else{writeArchive(loadArchive().filter(x=>x.id!==d.id))}renderArchive()}})}
for(let i=3;i<=16;i++)P.add(new Option(i+' 人',i));P.value=6;spies();storyPresets();renderArchive();document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>setMode(x.dataset.mode));[A,B,NA,NB].forEach(x=>x.oninput=preview);P.onchange=spies;$('randomStory').onclick=randomStory;$('start').onclick=()=>{if(build())handoff()};$('reveal').onclick=secret;$('next').onclick=()=>{state.i++;state.i>=state.players.length?ready():handoff()};$('restart').onclick=()=>{if(build())handoff()};$('back').onclick=()=>{renderArchive();show('setup')};$('revealGoal').onclick=()=>{$('goalSecret').textContent=storyGoal.value.trim();$('revealGoal').classList.add('hidden')};$('addRecord').onclick=addRecord;$('undoRecord').onclick=undoRecord;$('clearRecord').onclick=clearRecord;$('saveStory').onclick=saveCurrentStory;$('copyStory').onclick=()=>copyText(storyText(currentStoryData(),true));$('downloadStory').onclick=()=>downloadText(storyText(currentStoryData(),true),storyTheme.value.trim());$('recordText').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')addRecord()});document.addEventListener('keydown',e=>{if(!['Space','Enter'].includes(e.code)||['TEXTAREA','INPUT','SELECT'].includes(document.activeElement.tagName))return;if(screens.handoff.classList.contains('active'))$('reveal').click();else if(screens.secret.classList.contains('active'))$('next').click()});setMode('flavor');
})();